from django.urls import path
from . import views

app_name = "studiq_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('daftar_kelas', views.daftar_kelas, name='daftar_kelas'),
    path('tentang_kami', views.tentang_kami, name='tentang_kami'),
    path('FAQs', views.FAQs, name='FAQs'),
    path('login', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('daftar_materi', views.daftar_materi, name='daftar_materi'),
    path('home', views.home, name="home"),
    path('materi2/', views.materi2, name='materi2'),
    path('belajar/', views.belajar, name='belajar'),
    path('video/', views.video, name='video'),
    path('materi/<str:kelas>/<str:mapel>/', views.materi_view, name='materi'),
    path('profil', views.profil, name='profil'),
    path('pengaturan', views.pengaturan, name='pengaturan'),


    # TAMBAHAN DARI RIFDAH DAN YANG LAINNYA
    path('ipa4_1/', views.ipa4_1, name='ipa4_1'),
    path('materiipa4_1.1/', views.materiipa4_11, name='materiipa4_1.1'),
    path('materiipa4_1.2/', views.materiipa4_12, name='materiipa4_1.2'),
    path('materiipa4_1.3/', views.materiipa4_13, name='materiipa4_1.3'),
    path('videoipa/<int:order>/', views.videoipa, name='videoipa'),
    path('ipa4_2/', views.ipa4_2, name='ipa4_2'),
    path('materiipa4_2.1/', views.materiipa4_21, name='materiipa4_2.1'),
    path('materiipa4_2.2/', views.materiipa4_22, name='materiipa4_2.2'),
    path('materiipa4_2.3/', views.materiipa4_23, name='materiipa4_2.3'),
    path('video2ipa/<int:order>/', views.video2ipa, name='video2ipa'),
    path('ipa5_1/', views.ipa5_1, name='ipa5_1'),
    path('materiipa5_1.1/', views.materiipa5_11, name='materiipa5_1.1'),
    path('materiipa5_1.2/', views.materiipa5_12, name='materiipa5_1.2'),
    path('materiipa5_1.3/', views.materiipa5_13, name='materiipa5_1.3'),
    path('videoipa5/<int:order>/', views.videoipa5, name='videoipa5'),
    path('materiipa4/<int:order>/', views.materiipa4, name='materiipa4'),
    path('materi2/', views.materi2, name='materi2'),
    path('belajar/', views.belajar, name='belajar'),
    path('video/', views.video, name='video'),
    path('materi1ing/', views.materi1ing, name='materi1ing'),
    path('materi2ing/', views.materi2ing, name='materi2ing'),
    path('belajaring/', views.belajaring, name='belajaring'),
    path('belajar2ing/', views.belajar2ing, name='belajar2ing'),
    path('videoing/<int:order>/', views.videoing, name='videoing'),
    path('video2ing/<int:order>/', views.video2ing, name='video2ing'),
    path('materi3ing/', views.materi3ing, name='materi3ing'),
    path('materi4ing/', views.materi4ing, name='materi4ing'),
    path('belajar3ing/', views.belajar3ing, name='belajar3ing'),
    path('belajar4ing/', views.belajar4ing, name='belajar4ing'),
    path('video3ing/<int:order>/', views.video3ing, name='video3ing'),
    path('video4ing/<int:order>/', views.video4ing, name='video4ing'),

    path('belajar-mtk', views.belajar_mtk, name='belajar-mtk'),
    path('materi-mtk', views.materimtk5_1, name='materi-mtk'),
    path('materi2-mtk', views.materimtk5_2, name="materi2-mtk"),
    path('materi-ipa', views.materiipa6_1, name="materi-ipa"),
    path('belajar3-mtk', views.belajarmtk3_6, name="belajar3-mtk"),
    path('belajar4-mtk', views.belajarmtk4_6, name="belajar4-mtk"),
    path('belajar5-ing', views.belajar5ing, name="belajar5-ing"),
    path('belajar6-ing', views.belajar6ing, name="belajar6-ing"),
    path('materi3-mtk', views.materimtk6_1, name="materi3-mtk"),
    path('materi4-mtk', views.materimtk6_2, name="materi4-mtk"),
    path('materi5-ing', views.materi5ing, name="materi5-ing"),
    path('materi6-ing', views.materi6ing, name="materi6-ing"),
    path('belajar-ipa', views.belajar_ipa, name="belajar-ipa"),
    path('belajar2-ipa', views.belajar2_ipa, name="belajar2-ipa"),
    path('materi-ipa', views.materiipa6_1, name="materi-ipa"),
    path('materi2-ipa', views.materiipa6_2, name="materi2-ipa"),
    path('belajar2-mtk', views.mtk_5, name="belajar2-mtk"),

    # path('belajar_mtk_kls4_1', views.belajarmtk4_1, name="belajar_mtk_kls4_1"),
    # path('belajar_mtk_kls4_2', views.belajarmtk4_2, name="belajar_mtk_kls4_2"),
    path('materi1_mtk_kls4', views.materimtk4_1, name="materi1_mtk_kls4"),
    path('materi2_mtk_kls4', views.materimtk4_2, name="materi2_mtk_kls4"),
    path('materi3_mtk_kls4', views.materimtk4_3, name="materi3_mtk_kls4"),
    path('materi4_mtk_kls4', views.materimtk4_4, name="materi4_mtk_kls4"),

    path('video1mtkkls4/<int:order>/', views.video1mtkkls4, name='video1_mtk_kls4'),
    path('video2mtkkls4/<int:order>/', views.video2mtkkls4, name='video2_mtk_kls4'),
    path('video3mtkkls4/<int:order>/', views.video3mtkkls4, name='video3_mtk_kls4'),
    path('video4mtkkls4/<int:order>/', views.video4mtkkls4, name='video4_mtk_kls4'),

    path('quiz/', views.quiz_page, name='quiz')

]